### ISSUE TITLE
boot: No such task (cljs)

### ISSUE THREAD

**Issue by Bost** [omcljs/om-cookbook#27]
It seems like there's no cljs task in current boot version. Could you please update the README.md?
(I can't really do it for you - my knowledge & experience of boot is about 10 minutes large)
thx

Bost

$ wget https://github.com/boot-clj/boot/releases/download/2.0.0-rc14/boot.sh
$ mv boot.sh boot && chmod a+x boot && mv boot ~/bin
$ boot -u
$ boot cljs -h
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No such task (cljs)
    data: {:file "/tmp/boot.user3212033756989114326.clj", :line 5}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such task (cljs)
     java.lang.IllegalArgumentException: No such task (cljs)
          boot.core/construct-tasks                          core.clj:  657
                                ...
                 clojure.core/apply                          core.clj:  624
               boot.user/eval240/fn  boot.user3212033756989114326.clj:    7
clojure.core/binding-conveyor-fn/fn                          core.clj: 1910
                                ...

**Comment by Bost** [comment]
Sorry I messed up something... everything's fine.

**Comment by helarqjsc** [comment]
I have the same error on Windows 7:
```
$ boot -u
#https://github.com/boot-clj/boot
#Sun Jul 12 19:28:22 GMT+05:00 2015
BOOT_CLOJURE_VERSION=1.6.0
BOOT_VERSION=2.1.2
#App version: 2.0.0

$ boot cljs
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No such task (cljs)
    data: {:file
           "C:\\Users\\shi\\AppData\\Local\\Temp\\boot.user845990110355623113.clj",
           :line 5}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such task (cljs)
     java.lang.IllegalArgumentException: No such task (cljs)
          boot.core/construct-tasks  core.clj:  665
                                ...
                 clojure.core/apply  core.clj:  624
                  boot.core/boot/fn  core.clj:  699
clojure.core/binding-conveyor-fn/fn  core.clj: 1910
                                ...
```
Any ideas on how to fix it?

**Comment by annapawlicka** [comment]
What directory are you trying to run boot from? It should be this project's directory.

**Comment by Deraen** [comment]
And specifically in the directory which has the `build.boot` file, e.g. recipes/boot-setup.
